### ISSUE TITLE
couleur des passes et des niveaux

### ISSUE THREAD

**Issue by laetitiamassa** [laetitiamassa/swingplicity#1]

**Comment by laetitiamassa** [comment]
couleurs passes : à trouver
couleurs soirées : principale (mauve)

**Comment by laetitiamassa** [comment]
voili voilou !

**Comment by brusselswcs** [comment]
Coucou Laetitia,

J'ai jeter un coup d'oeil rapide.
Level 2 et le Pass Manneken Piss doivent avoir la même couleur.
Level 3 et le Pass Atomium doivent avoir la même couleur pour comprendre le
lien.

Par contre, aussi, j'aurais mis tout le bloc du pass dans la couleur du
pass et pas uniquement le bord supérieur tout comme le bouton avec le prix
dans la couleur du pass.
Qu'en penses-tu? Est-ce possible?

Merci
Bisous
Sylvin

**Comment by laetitiamassa** [comment]
Hello sylvin,

Ok je change les couleurs niveau/pass : tu préfères que je mette du vert et du jaune (comme les niveaux) ? ou bien je mets les couleurs des pass pour les niveaux correspondants ?

Sinon pour le hoover des pass, ça prendre bcp plus de temps de le modifier aussi, donc je vais voir si je trouve encore du temps cette semaine, sinon dimanche/lundi je peux d’office m’y attaquer - ok ?

Laetitia Massa

---

Web entrepreneur & developer | Lawyer | Marketeer
http://linkedin.com/in/laetitiamassa http://linkedin.com/in/laetitiamassa

**Comment by brusselswcs** [comment]
vert et jaune me semble bien.
Ok pour le hoover. Par contre, est-il possible de déjà changer la couleur
du bouton avec le prix?

2015-06-29 14:45 GMT+02:00 Laetitia Massa notifications@github.com:

**Comment by laetitiamassa** [comment]
ok j'adapte la couleur du bouton now :) et tu peux créer une nouvelle issue pour le reste
