### ISSUE TITLE
Google form

### ISSUE THREAD

**Issue by brusselswcs** [laetitiamassa/swingplicity#13]
Problème d'affichage dans la popup sur smartphone.
Il est difficile d'atteindre le bas du formulaire.

**Comment by laetitiamassa** [comment]
peux-tu m'envoyer un screenshot stp ? je vais aussi tenter depuis mon smartphone

**Comment by laetitiamassa** [comment]
chez moi ça fonctionne (samsung galaxy s4 mini). Quid ?

**Comment by brusselswcs** [comment]
Sur iPhone pas moyen et sur mon s4 mini il faut chipoter pour y arriver. Il
n'affiche pas le bas quand on scroll au milieu mais seulement quand on
scroll sur le bord.
Anne envoie un print screen!

**Comment by brusselswcs** [comment]
<div>
    <iframe width="100%" height="980px" src="https://docs.google.com/forms/d/1KTizegRN2aLlNbfhZ5WRmaYztzfORqVzUTYND3Y0Xo0/viewform"/>
</div>

**Comment by brusselswcs** [comment]
J'ai remplacé tous les bouttons pour qu'il redirige vers Google Form.
