### ISSUE TITLE
Référencement Google

### ISSUE THREAD

**Issue by brusselswcs** [laetitiamassa/swingplicity#14]
Isaline m'a fait remarqué que dans Google, quand on cheche "Swingplicity" le premier hit est "www.swingplicitybrussels.be/en" ce qui n'existe plus.
Y a-t-il moyen de faire qqch pour rediriger cela vers le site?
En faite, l'idéal serait que n'importe quoi qui n'existe pas retourne vers la home page.

**Comment by laetitiamassa** [comment]
oui, il faut que vous fassiez des redirections (avec ovh) de toutes les url non existantes vers l’url existante.
Google prend un petit temps avant d’adapter ses résultats de recherche.

Laetitia Massa

---

Web entrepreneur & developer | Lawyer | Marketeer
http://linkedin.com/in/laetitiamassa http://linkedin.com/in/laetitiamassa

**Comment by brusselswcs** [comment]
Ok je vais chercher!

**Comment by brusselswcs** [comment]
J'ai changé la page 404.html pour qu'elle redirige vers la homepage du site.
