### ISSUE TITLE
January 2016 dans le header

### ISSUE THREAD

**Issue by brusselswcs** [laetitiamassa/swingplicity#5]
Ajouter "Janvier 2016"/"January 2016" dans le header du site (à côté du logo Swingplicity) -> le prévoir dans le fichier traduction ?
![capture](https://cloud.githubusercontent.com/assets/12573290/8383708/3eec395c-1c3c-11e5-81b3-bd5a9bef9e33.JPG)

**Comment by laetitiamassa** [comment]
ok ajouté, en couleur mauve et en italique
Oui, je l'ai traduit :)

**Comment by laetitiamassa** [comment]
finalement ce sera en gris ;) - plus discret
