### ISSUE TITLE
Search Engine

### ISSUE THREAD

**Issue by brusselswcs** [laetitiamassa/swingplicity#7]
Use Description and keyword for Search Engine.
If we can change the text via the language file, this would be awesome. :)
EN
meta name="keywords" content="Swingplicity, Brussels, Dance, West Coast Swing, WCS, Workshop, Event"
meta name="description" content="Brussels WCS invites you to the second edition of the SWINGPLICITY BRUSSELS"
FR
meta name="keywords" content="Swingplicity, Bruxelles, Danse, West Coast Swing, WCS, Workshop, Stage"
meta name="description" content="Brussels WCS vous convie à la deuxième édition du SWINGPLICITY BRUSSELS"

**Comment by laetitiamassa** [comment]
fait en deux langues
