### ISSUE TITLE
documents pdf

### ISSUE THREAD

**Issue by laetitiamassa** [laetitiamassa/swingplicity#8]
- hotel
- charte (à recevoir)

**Comment by laetitiamassa** [comment]
@brusselswcs il faudra me dire quand tu auras fait le lien avec ton site pour que je change la localisation du document vers swingplicitybrussels.be

Pour info, j'ai mis la charte en anglais.

**Comment by brusselswcs** [comment]
Là je t'avoue que je n'ai pas tout compris!
Pour info l'URL principale est https://swingplicity.brussels

**Comment by laetitiamassa** [comment]
en fait les docs pdf sont logés en mode public, donc avec un lien absolu (http.domain.tld) et non relatif (hotel_path, home_path, etc).  La conséquence est qu’il faut que j’indique un lien vers la « vraie » adresse finale (idéalement).
De toute façon no stress car quand les gens cliquent, ils ouvrent un nouvel onglet => tant que tu n’as pas fait le lien et que je n’ai pas changé l’adresse, l’accès effectif au document n’est pas du tout perturbé :)

Pour l’instant, ils sont donc à http://swingplicity.herokuapp.com/charter_en.pdf http://swingplicity.herokuapp.com/charter_en.pdf et http://swingplicity.herokuapp.com/hotel_form.pdf http://swingplicity.herokuapp.com/hotel_form.pdf 

A plus,
Laety

Laetitia Massa

---

Web entrepreneur & developer | Lawyer | Marketeer
http://linkedin.com/in/laetitiamassa http://linkedin.com/in/laetitiamassa
